// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptihuoxqjymxvvaotzaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0aWh1b3hxanlteHZ2YW90emF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNzE0MjEsImV4cCI6MjA1Nzc0NzQyMX0.ZJkuRTEq20KnGQjl91e5FGg5YiYukh08Nn57x41AYw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);